In [1]:
import numpy as np

In [19]:
data=np.random.randint(0,10,10)

In [3]:
data

array([4, 0, 3, 2, 8, 2, 0, 2, 5, 3], dtype=int32)

In [4]:
data.shape

(10,)

In [8]:
data.reshape(2,5)

array([[4, 0, 3, 2, 8],
       [2, 0, 2, 5, 3]], dtype=int32)

In [9]:
data.reshape(5,2)

array([[4, 0],
       [3, 2],
       [8, 2],
       [0, 2],
       [5, 3]], dtype=int32)

In [10]:
data.ravel()

array([4, 0, 3, 2, 8, 2, 0, 2, 5, 3], dtype=int32)

In [20]:
data = np.array_split(data,6)
data

[array([1, 5], dtype=int32),
 array([6, 5], dtype=int32),
 array([9, 4], dtype=int32),
 array([5, 0], dtype=int32),
 array([6], dtype=int32),
 array([4], dtype=int32)]

In [21]:
import numpy as np
data=np.random.randint(0,10,10)
np.hsplit(data,5)

[array([9, 5], dtype=int32),
 array([9, 2], dtype=int32),
 array([3, 7], dtype=int32),
 array([3, 4], dtype=int32),
 array([1, 0], dtype=int32)]

In [44]:
data=np.random.randint(0,10,(20,4))
data

array([[8, 1, 1, 1],
       [0, 9, 9, 0],
       [9, 6, 3, 5],
       [9, 4, 2, 5],
       [3, 8, 6, 3],
       [6, 4, 8, 6],
       [5, 3, 0, 8],
       [7, 8, 2, 5],
       [6, 5, 4, 0],
       [3, 7, 6, 6],
       [6, 0, 0, 5],
       [7, 1, 5, 1],
       [9, 4, 1, 5],
       [1, 3, 9, 2],
       [9, 0, 9, 0],
       [5, 1, 7, 3],
       [1, 0, 1, 6],
       [1, 2, 8, 7],
       [0, 4, 5, 1],
       [8, 6, 0, 0]], dtype=int32)

In [53]:
##index based spliting
np.hsplit(data,[4,8])

[array([[8, 1, 1, 1],
        [0, 9, 9, 0],
        [9, 6, 3, 5],
        [9, 4, 2, 5],
        [3, 8, 6, 3],
        [6, 4, 8, 6],
        [5, 3, 0, 8],
        [7, 8, 2, 5],
        [6, 5, 4, 0],
        [3, 7, 6, 6],
        [6, 0, 0, 5],
        [7, 1, 5, 1],
        [9, 4, 1, 5],
        [1, 3, 9, 2],
        [9, 0, 9, 0],
        [5, 1, 7, 3],
        [1, 0, 1, 6],
        [1, 2, 8, 7],
        [0, 4, 5, 1],
        [8, 6, 0, 0]], dtype=int32),
 array([], shape=(20, 0), dtype=int32),
 array([], shape=(20, 0), dtype=int32)]

In [31]:
data=np.random.randint(0,10,(2,4))
data

array([[7, 8, 2, 2],
       [8, 2, 6, 0]], dtype=int32)

In [47]:
np.hsplit(data,2)

[array([[8, 1],
        [0, 9],
        [9, 6],
        [9, 4],
        [3, 8],
        [6, 4],
        [5, 3],
        [7, 8],
        [6, 5],
        [3, 7],
        [6, 0],
        [7, 1],
        [9, 4],
        [1, 3],
        [9, 0],
        [5, 1],
        [1, 0],
        [1, 2],
        [0, 4],
        [8, 6]], dtype=int32),
 array([[1, 1],
        [9, 0],
        [3, 5],
        [2, 5],
        [6, 3],
        [8, 6],
        [0, 8],
        [2, 5],
        [4, 0],
        [6, 6],
        [0, 5],
        [5, 1],
        [1, 5],
        [9, 2],
        [9, 0],
        [7, 3],
        [1, 6],
        [8, 7],
        [5, 1],
        [0, 0]], dtype=int32)]

In [46]:
np.hsplit(data,1)

[array([[8, 1, 1, 1],
        [0, 9, 9, 0],
        [9, 6, 3, 5],
        [9, 4, 2, 5],
        [3, 8, 6, 3],
        [6, 4, 8, 6],
        [5, 3, 0, 8],
        [7, 8, 2, 5],
        [6, 5, 4, 0],
        [3, 7, 6, 6],
        [6, 0, 0, 5],
        [7, 1, 5, 1],
        [9, 4, 1, 5],
        [1, 3, 9, 2],
        [9, 0, 9, 0],
        [5, 1, 7, 3],
        [1, 0, 1, 6],
        [1, 2, 8, 7],
        [0, 4, 5, 1],
        [8, 6, 0, 0]], dtype=int32)]

In [55]:
np.vsplit(data,[2,4,6])

[array([[8, 1, 1, 1],
        [0, 9, 9, 0]], dtype=int32),
 array([[9, 6, 3, 5],
        [9, 4, 2, 5]], dtype=int32),
 array([[3, 8, 6, 3],
        [6, 4, 8, 6]], dtype=int32),
 array([[5, 3, 0, 8],
        [7, 8, 2, 5],
        [6, 5, 4, 0],
        [3, 7, 6, 6],
        [6, 0, 0, 5],
        [7, 1, 5, 1],
        [9, 4, 1, 5],
        [1, 3, 9, 2],
        [9, 0, 9, 0],
        [5, 1, 7, 3],
        [1, 0, 1, 6],
        [1, 2, 8, 7],
        [0, 4, 5, 1],
        [8, 6, 0, 0]], dtype=int32)]

In [54]:
np.vsplit(data,5)

[array([[8, 1, 1, 1],
        [0, 9, 9, 0],
        [9, 6, 3, 5],
        [9, 4, 2, 5]], dtype=int32),
 array([[3, 8, 6, 3],
        [6, 4, 8, 6],
        [5, 3, 0, 8],
        [7, 8, 2, 5]], dtype=int32),
 array([[6, 5, 4, 0],
        [3, 7, 6, 6],
        [6, 0, 0, 5],
        [7, 1, 5, 1]], dtype=int32),
 array([[9, 4, 1, 5],
        [1, 3, 9, 2],
        [9, 0, 9, 0],
        [5, 1, 7, 3]], dtype=int32),
 array([[1, 0, 1, 6],
        [1, 2, 8, 7],
        [0, 4, 5, 1],
        [8, 6, 0, 0]], dtype=int32)]

In [56]:
data=np.random.randint(0,10,(4,4))
data

array([[2, 0, 3, 7],
       [1, 3, 8, 6],
       [5, 2, 4, 3],
       [6, 9, 8, 2]], dtype=int32)

In [57]:
data1=np.random.randint(0,10,(4,1))
data1

array([[1],
       [0],
       [1],
       [2]], dtype=int32)

In [58]:
data+data1

array([[ 3,  1,  4,  8],
       [ 1,  3,  8,  6],
       [ 6,  3,  5,  4],
       [ 8, 11, 10,  4]], dtype=int32)

In [60]:
data=np.random.randint(0,10,(4,4))
data

array([[1, 9, 8, 4],
       [1, 0, 7, 6],
       [2, 8, 0, 8],
       [2, 8, 8, 1]], dtype=int32)

In [59]:
data1=np.random.randint(0,10,(1,4))
data1


array([[0, 2, 2, 8]], dtype=int32)

In [61]:
data+data1

array([[ 1, 11, 10, 12],
       [ 1,  2,  9, 14],
       [ 2, 10,  2, 16],
       [ 2, 10, 10,  9]], dtype=int32)

In [62]:
data1=np.random.randint(0,10,(4,1))
data1

array([[0],
       [5],
       [3],
       [2]], dtype=int32)

In [63]:
data=np.random.randint(0,10,(1,4))
data

array([[7, 8, 1, 6]], dtype=int32)

In [64]:
data+data1

array([[ 7,  8,  1,  6],
       [12, 13,  6, 11],
       [10, 11,  4,  9],
       [ 9, 10,  3,  8]], dtype=int32)

In [67]:
data=np.random.randint(1,10,(5,5))
data

array([[8, 9, 5, 8, 6],
       [7, 7, 8, 5, 5],
       [4, 5, 7, 6, 2],
       [4, 6, 2, 8, 7],
       [9, 4, 4, 9, 5]], dtype=int32)

In [69]:
d_matrix=[]
for i in data:
    for j in data:
        distance=np.sqrt((((i-j)**2)).sum())
        d_matrix.append(int(distance))

In [70]:
np.array(d_matrix).reshape(5,5)

array([[0, 4, 7, 5, 5],
       [4, 0, 4, 7, 6],
       [7, 4, 0, 7, 7],
       [5, 7, 7, 0, 6],
       [5, 6, 7, 6, 0]])

In [71]:
marks=np.random.randint(1,100,100)
marks

array([61, 14, 41, 50, 75, 45, 49, 26, 96, 69, 23, 54, 85,  6, 90,  7, 53,
       88, 25, 15, 26, 18, 94, 30, 27, 63, 43, 13, 75,  4,  6, 38,  7, 43,
       12, 49, 99, 28, 85, 24, 71, 68, 81, 88, 10, 40, 56, 14, 65, 51, 66,
       27, 98, 92, 51, 82, 67, 82, 94, 45, 22, 26, 34, 25, 89, 32, 75, 74,
       79, 71,  9, 58, 20, 36,  1, 82, 39, 91, 28,  3, 36, 68, 19, 87, 73,
       16, 41, 70, 39, 71, 75, 33, 22, 97, 37, 34, 39, 96, 93, 89],
      dtype=int32)

In [72]:
marks.shape

(100,)

In [74]:
mark=(marks>np.mean(marks).sum())

In [77]:
d=[]
for i in mark:
    for j in marks:
        d.append(int(abs(i-j)))


In [82]:
d

[60,
 13,
 40,
 49,
 74,
 44,
 48,
 25,
 95,
 68,
 22,
 53,
 84,
 5,
 89,
 6,
 52,
 87,
 24,
 14,
 25,
 17,
 93,
 29,
 26,
 62,
 42,
 12,
 74,
 3,
 5,
 37,
 6,
 42,
 11,
 48,
 98,
 27,
 84,
 23,
 70,
 67,
 80,
 87,
 9,
 39,
 55,
 13,
 64,
 50,
 65,
 26,
 97,
 91,
 50,
 81,
 66,
 81,
 93,
 44,
 21,
 25,
 33,
 24,
 88,
 31,
 74,
 73,
 78,
 70,
 8,
 57,
 19,
 35,
 0,
 81,
 38,
 90,
 27,
 2,
 35,
 67,
 18,
 86,
 72,
 15,
 40,
 69,
 38,
 70,
 74,
 32,
 21,
 96,
 36,
 33,
 38,
 95,
 92,
 88,
 61,
 14,
 41,
 50,
 75,
 45,
 49,
 26,
 96,
 69,
 23,
 54,
 85,
 6,
 90,
 7,
 53,
 88,
 25,
 15,
 26,
 18,
 94,
 30,
 27,
 63,
 43,
 13,
 75,
 4,
 6,
 38,
 7,
 43,
 12,
 49,
 99,
 28,
 85,
 24,
 71,
 68,
 81,
 88,
 10,
 40,
 56,
 14,
 65,
 51,
 66,
 27,
 98,
 92,
 51,
 82,
 67,
 82,
 94,
 45,
 22,
 26,
 34,
 25,
 89,
 32,
 75,
 74,
 79,
 71,
 9,
 58,
 20,
 36,
 1,
 82,
 39,
 91,
 28,
 3,
 36,
 68,
 19,
 87,
 73,
 16,
 41,
 70,
 39,
 71,
 75,
 33,
 22,
 97,
 37,
 34,
 39,
 96,
 93,
 89,
 61,
 14,
 41,
 5